th-96: Add custom map design and tow-truck icon
BinaryStudioAcademy/bsa-2023-towhub pull request #105
Opened 2023-08-27 22:45 UTC by h0wter

Created a custom design for the map and added a tow-truck icon.

![map](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/91832203/c0478725-4f15-4bc7-a06a-cb75d40fab30)

2023-08-28 07:37 UTC, albsbz commented on frontend/src/libs/packages/map/map.package.ts
> +      mapId: '2db763871084f8b6',
If this from google project, maybe better move it to .ENV?

2023-08-28 13:16 UTC, Druxight requested changes

2023-08-28 13:16 UTC, Druxight commented on frontend/src/libs/packages/map/map.package.ts
> +      mapId: '2db763871084f8b6',
use JSON config

2023-09-02 16:46 UTC, PavloSukhinin commented on frontend/src/libs/packages/map/map.package.ts
> +import truckImg from 'src/assets/img/tow-truck.png';
```suggestion
import truckImg from '~/assets/img/tow-truck.png';
```

2023-09-04 07:11 UTC, kalinkaaaa14 commented on frontend/src/libs/packages/map/map.config.json
> +        "visibility": "off"
quick question - do we need to add such many feature types with visibility off? are they enabled by default?

2023-09-04 08:08 UTC, h0wter commented on frontend/src/libs/packages/map/map.config.json
> +        "visibility": "off"
The standard map shows all places, captions. To match the design I had to turn off various points of interest. I turned off only what does not match the design.

2023-09-04 08:19 UTC, kalinkaaaa14 commented on frontend/src/libs/packages/map/map.config.json
> +        "visibility": "off"
ok, got it, thank you

2023-09-04 08:19 UTC, kalinkaaaa14 approved these changes

2023-09-04 08:26 UTC, DmytroVoronkov approved these changes

2023-09-04 10:10 UTC, Druxight approved these changes

2023-09-04 10:10 UTC, merged