th-108: Google autocomplete
BinaryStudioAcademy/bsa-2023-towhub pull request #113
Opened 2023-08-29 14:12 UTC by DmytroVoronkov

- Added location input component 

![image](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/103923623/abc5216d-57a7-4a2c-9aa7-91df103b52c3)

2023-08-31 15:57 UTC, Druxight requested changes

2023-08-31 15:57 UTC, Druxight commented on frontend/src/libs/components/location-input/styles.module.scss
> +  max-width: 327px;
where the value came from

2023-08-31 15:57 UTC, Druxight commented on frontend/src/libs/components/modal/styles.module.scss
> +@media only screen and (width < 768px) {
we should have screen sizes in the vars.scss

2023-08-31 16:36 UTC, DmytroVoronkov commented on frontend/src/libs/components/location-input/styles.module.scss
> +  max-width: 327px;
I took styles from input component

2023-09-04 07:56 UTC, kalinkaaaa14 approved these changes

2023-09-04 17:00 UTC, Druxight approved these changes

2023-09-04 18:01 UTC, PavloSukhinin approved these changes

2023-09-04 18:17 UTC, merged