th-112: Add query parameters service
BinaryStudioAcademy/bsa-2023-towhub pull request #114
Opened 2023-08-29 14:43 UTC by h0wter

All functions work with either single or multiple arguments.
`getQueryParameters('param')` or `getQueryParameters('param', 'param1')`
`removeQueryParameters('param')` or `removeQueryParameters('param', 'param1')`
`setQueryParameters({param: value})` or `setQueryParameters({param: value, param1: value1})`
`setQueryParameters` can take both a string and a number as a property value.

2023-08-31 16:00 UTC, Druxight submitted a review, later dismissed

2023-09-02 11:19 UTC, PavloSukhinin requested changes

2023-09-02 11:19 UTC, PavloSukhinin commented on frontend/src/libs/hooks/use-query-parameters/use-query-parameters.hook.ts
> +import { useCallback, useSearchParameters } from '../hooks.js';
Circular dependency, be careful with that

2023-09-02 11:19 UTC, PavloSukhinin commented on frontend/src/libs/hooks/use-query-parameters/use-query-parameters.hook.ts
> +type Parameters = Record<string, string | number>;
rename this, Parameters is build-in TS type

2023-09-04 10:47 UTC, DmytroVoronkov approved these changes

2023-09-05 15:43 UTC, Some14u approved these changes
Simple and clean. I like it, however in my opinion it lacks possibility to pass and handle default values.
For example, if i need some key value, which has it's own default, i'd expect this to return the default value when there is no corresponding key in the query.

2023-09-05 15:43 UTC, Some14u commented on frontend/src/libs/hooks/use-query-parameters/use-query-parameters.hook.ts
> +      if (keys.length > 1) {
consider the case, when there is no parameters being passed. I think you can add "remove everything" for that particular case.

2023-09-08 14:04 UTC, PavloSukhinin approved these changes

2023-09-08 14:29 UTC, kalinkaaaa14 approved these changes

2023-09-08 14:39 UTC, merged