th-109: Sign up markup
BinaryStudioAcademy/bsa-2023-towhub pull request #115
Opened 2023-08-29 16:26 UTC by TetianaDoroshko

The flow starts from the button 'Sign in' in Header, then Welcome page with 2 options of users and then Auth page with 2 variant of form depending on type of user.

![image](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/95139041/8de8ad71-88cd-4bf5-88dd-341d86cd5824)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/95139041/89223ae8-4a9d-4217-913c-ee7f1f8f6bb4)

2023-08-29 16:27 UTC, TetianaDoroshko commented
A few marks: 

1. so wierd code:  
```typescript 
  const location: Location = useLocation(); 
  const mode = location.state as string; 
```  
because the linter considers unsafe location.state type unsafe and doesn't let me destructurize normally. 
  
2. I'm not sure should I do separate actions for sign-up for customer and business owner. But I decided to use one action with additional parameter 'mode'.

2023-08-30 07:21 UTC, PavloSukhinin requested changes

2023-08-30 07:21 UTC, PavloSukhinin commented on frontend/src/libs/components/business-card/business-card.tsx
> +import { AuthMode } from 'src/libs/enums/enums.js';
```suggestion
import { AuthMode } from '~/libs/enums/enums.js';
```

2023-08-30 07:21 UTC, PavloSukhinin commented on frontend/src/libs/components/customer-card/customer-card.tsx
> +import { AuthMode } from 'src/libs/enums/enums.js';
```suggestion
import { AuthMode } from '~/libs/enums/enums.js';
```

2023-08-30 07:21 UTC, PavloSukhinin commented on frontend/src/packages/auth/auth-api.ts
> +    mode: string,
```suggestion
    mode: Valueof<typeof AuthMode>,
```

2023-08-30 07:21 UTC, PavloSukhinin commented on frontend/src/pages/auth/auth.tsx
> +  const mode = location.state as string;
> because the linter considers location.state type unsafe and doesn't let me destructurize normally.

That ok, because Location state has any type

2023-08-30 07:21 UTC, PavloSukhinin commented on frontend/src/pages/auth/components/sign-up-form/libs/constants.ts
> +import { type BusinessSignUpRequestDto } from 'shared/build/packages/users/libs/types/business-sign-up-request-dto.type';
```suggestion
import { type BusinessSignUpRequestDto } from '~/lib/types....';
```

2023-08-30 07:21 UTC, PavloSukhinin commented on frontend/src/pages/auth/components/sign-up-form/libs/fields.ts
> +import { type BusinessSignUpRequestDto } from 'shared/build/packages/users/libs/types/business-sign-up-request-dto.type';
```suggestion
import { type BusinessSignUpRequestDto } from '~/lib/types/types.js';
```

2023-08-30 07:21 UTC, PavloSukhinin commented on frontend/src/pages/auth/components/sign-up-form/libs/fields.ts
> +  { label: FormLabel.PHONE, placeholder: 'Enter your phone', name: 'phone' },
Let's be consistent and use enum for `name` property

2023-08-30 07:21 UTC, PavloSukhinin commented on frontend/src/pages/auth/components/sign-up-form/libs/fields.ts
> +  {
Line above - same about enum

2023-08-30 07:21 UTC, PavloSukhinin commented on frontend/src/pages/auth/components/sign-up-form/sign-up-form.tsx
> +import { businessSignUpValidationSchema } from 'shared/build/index.js';
from '~/packages/users/users.js'

2023-08-30 07:21 UTC, PavloSukhinin commented on frontend/src/pages/auth/components/sign-up-form/sign-up-form.tsx
> +  mode: string;
`mode: Valueof<typeof AuthMode>`

2023-08-30 07:21 UTC, PavloSukhinin commented on frontend/src/pages/auth/components/sign-up-form/sign-up-form.tsx
> +      <h3 className={styles.title}>Sign Up</h3>
let's use some styles from typography.scss

2023-08-30 07:21 UTC, PavloSukhinin commented on frontend/src/pages/auth/components/sign-up-form/sign-up-form.tsx
> +      <p className={styles.text}>
Can we utilize .text-sm here?

2023-08-30 12:06 UTC, PavloSukhinin submitted a review, later dismissed

2023-08-30 12:36 UTC, PavloSukhinin approved these changes

2023-08-30 12:37 UTC, Druxight approved these changes

2023-08-30 12:37 UTC, merged