th-117: Sign-In flow
BinaryStudioAcademy/bsa-2023-towhub pull request #121
Opened 2023-08-31 10:30 UTC by DmytroVoronkov

- Added findByOwnerId in business service to get user business
- Added data in auth slice
- Added useAuthNavigate hook to redirect users after authorization

2023-08-31 12:15 UTC, h0wter commented on frontend/src/slices/auth/auth.slice.ts
> +type User = {
Maybe we should move this to types? We will need it in thunks and other parts.

2023-08-31 15:33 UTC, PavloSukhinin requested changes
I believe we don't need to create separate type for Store, and if we'll have to - it should be declared on frontend

2023-08-31 15:33 UTC, PavloSukhinin commented on backend/src/packages/users/libs/types/user-models.type.ts
>  type UserEntityObjectWithGroupT = UserEntityObjectT & {
This type should be moved into a shared module, then we'll be able to use it as return type for Sign-in on backend and signIn here `frontend/src/packages/auth/auth-api.ts`. In other terms - we need to create a contract between frontend and backend

2023-08-31 15:33 UTC, PavloSukhinin commented on frontend/src/libs/hooks/use-auth-navigate/use-auth-navigate.hook.ts
> +import { type UserSignInResponseDto } from 'shared/build';
Import it from corresponding types dir on frontend.

2023-08-31 15:33 UTC, PavloSukhinin commented on frontend/src/slices/auth/auth.slice.ts
> +import { type UserStore } from 'shared/build/packages/users/users.js';
Don't use direct imports from shared, user types should be re-exported though `frontend/src/packages/users/libs/types/types.ts`

2023-08-31 15:33 UTC, PavloSukhinin commented on frontend/src/slices/auth/auth.slice.ts
> +      state.token = action.payload.accessToken;
Remove it, we don't need token in store.
Instead - use thunk (sign-in action) to set this token to local storage. Use our storage service

2023-08-31 15:33 UTC, PavloSukhinin commented on shared/src/packages/users/libs/types/user-store.type.ts
> +type UserStore = {
Can we re-use `UserSignInResponseDto` instead of this type?

2023-08-31 15:33 UTC, PavloSukhinin commented on backend/src/packages/users/libs/types/user-models.type.ts
> +import { type BusinessEntityT } from 'shared/build/index.js';
from '~/packages/business/libs/types/types.ts`

2023-08-31 15:33 UTC, PavloSukhinin commented on backend/src/packages/auth/auth.service.ts
> +    );
Not sure why we returning business during sign-in, but OK

2023-08-31 15:33 UTC, PavloSukhinin commented on backend/src/packages/auth/auth.service.ts
> +      business: userBusiness,
Remove comment on line below, please

2023-08-31 15:33 UTC, PavloSukhinin commented on backend/src/packages/auth/auth.controller.ts
> +      path: AuthApiPath.SIGN_UP,
not sure why this was changed in this PR

2023-08-31 15:33 UTC, PavloSukhinin commented on frontend/src/pages/auth/auth.tsx
> +          authNavigate(user);
let's rename this one, verbBlahBlah

2023-08-31 15:33 UTC, PavloSukhinin commented on frontend/src/libs/hooks/use-auth-navigate/use-auth-navigate.hook.ts
> +        navigate('/dashboard');
this should be in AppRoute enum

2023-08-31 15:33 UTC, PavloSukhinin commented on frontend/src/libs/hooks/use-auth-navigate/use-auth-navigate.hook.ts
> +      case 'business': {
This should be UserGroupKey enum

2023-09-01 07:48 UTC, PavloSukhinin requested changes
Don't forget to update swagger documentation for sign-in endpoint

2023-09-01 07:48 UTC, PavloSukhinin commented on backend/src/packages/users/libs/types/user-models.type.ts
> +  business?: BusinessEntityT | null;
Can we make it required? (remove `?`)

2023-09-01 07:48 UTC, PavloSukhinin commented on frontend/src/slices/auth/actions.ts
> +  const result = await authApi.signIn(signInPayload);
const { authApi, localStorage } = extra

pass it through extra arguments.

2023-09-01 07:48 UTC, PavloSukhinin commented on frontend/src/slices/auth/actions.ts
> +  await LocalStorage.set('token', result.accessToken);
Let's create LocalStorageKey enum

2023-09-01 11:06 UTC, PavloSukhinin requested changes

2023-09-01 11:06 UTC, PavloSukhinin commented on frontend/src/libs/packages/store/store.package.ts
> +  LocalStorage: typeof LocalStorage;
```suggestion
  localStorage: typeof LocalStorage;
```
🥲

2023-09-01 11:59 UTC, PavloSukhinin approved these changes

2023-09-01 12:02 UTC, Druxight approved these changes

2023-09-01 12:02 UTC, merged