th-202: Implement the 404 page according to the design
BinaryStudioAcademy/bsa-2023-towhub pull request #206
Opened 2023-09-07 07:32 UTC by DmytroVoronkov

- Added styles to not-found page

![image](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/103923623/a31b813a-eafe-4be9-8141-275b1b619f19)

2023-09-07 10:01 UTC, TetianaDoroshko reviewed
Can we use already existing src/assets/img/auth-page-bg.svg? It contains tow-truck and 2 dashlines.

2023-09-07 10:10 UTC, DmytroVoronkov commented
In given desing there was only 1 dashline, so i decided to create a new svg

2023-09-07 10:14 UTC, TetianaDoroshko commented
I think it would be more consistently use the same bg.

2023-09-07 16:57 UTC, Druxight requested changes

2023-09-07 16:57 UTC, Druxight commented on frontend/src/pages/not-found/not-found.tsx
> +      GO TO HOMEPAGE
Use the button component instead

2023-09-07 17:23 UTC, TetianaDoroshko approved these changes

2023-09-08 14:36 UTC, h0wter approved these changes

2023-09-11 10:45 UTC, h0wter approved these changes

2023-09-11 10:50 UTC, kalinkaaaa14 commented on frontend/src/pages/not-found/not-found.tsx
> +import styles from './style.module.scss';
```suggestion
import styles from './styles.module.scss';
```

2023-09-11 11:03 UTC, kalinkaaaa14 commented on frontend/src/pages/not-found/styles.module.scss
> +@import "../../assets/css/vars.scss";
src/assets/css/vars.scss

2023-09-11 11:05 UTC, PavloSukhinin approved these changes, later dismissed

2023-09-11 11:05 UTC, PavloSukhinin commented on frontend/src/pages/not-found/styles.module.scss
> +@import "../../assets/css/vars.scss";
```suggestion
@import "src/assets/css/vars.scss";
```

2023-09-11 11:17 UTC, PavloSukhinin approved these changes

2023-09-11 11:22 UTC, merged