th-218: Order Page
BinaryStudioAcademy/bsa-2023-towhub pull request #233
Opened 2023-09-12 18:49 UTC by DmytroVoronkov

- Added order page
- Added orders slice
- Added orders Api
- Changed map and autocomplete

![image](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/103923623/2d1ea214-18e1-4bc0-bcaf-3a6d21929b11)

2023-09-13 07:57 UTC, kalinkaaaa14 commented on frontend/src/slices/orders/actions.ts
> +  return ordersApi.createOrder(payload);
can we add some toast notification message here?

2023-09-13 07:57 UTC, kalinkaaaa14 commented on frontend/src/pages/order/order.tsx
> +          />
chosen truck will be passed through props, why do you hardcoded values here?

2023-09-13 07:57 UTC, kalinkaaaa14 commented on frontend/src/pages/order/order.tsx
> +        });
why do you need unwrap here? can't u write just 
 dispatch(orderActions.createOrder({ ...payload, driverId }));

2023-09-13 07:57 UTC, kalinkaaaa14 commented on frontend/src/pages/order/order.tsx
> +  });
is it the location of the customer? can you remove mock data and find real geo coordinates?

2023-09-13 07:57 UTC, kalinkaaaa14 commented on frontend/src/pages/order/libs/components/order-form.tsx
> +  onDestinationChange: ((place: google.maps.LatLngLiteral) => void) | undefined;
```suggestion
  onLocationChange?: ((place: google.maps.LatLngLiteral) => void);
  onDestinationChange?: ((place: google.maps.LatLngLiteral) => void);
```

2023-09-13 07:57 UTC, kalinkaaaa14 commented on frontend/src/pages/order/libs/components/libs/fields.ts
> +const OrderFormFields: FormField<OrderCreateRequestDto>[] = [
```suggestion
const orderFormFields: FormField<OrderCreateRequestDto>[] = [
```

2023-09-13 07:57 UTC, kalinkaaaa14 commented on frontend/src/pages/order/libs/components/libs/constants.ts
> +const CREATE_ORDER_DEFAULT_PAYLOAD = {
add type here

2023-09-13 07:57 UTC, kalinkaaaa14 commented on frontend/src/libs/components/form/form.tsx
>  };
```suggestion
  onLocationChange?: ((place: google.maps.LatLngLiteral) => void);
  onDestinationChange?:((place: google.maps.LatLngLiteral) => void);
};
```

2023-09-13 11:39 UTC, TetianaDoroshko commented on frontend/src/libs/components/router/router.tsx
>          <Route path={AppRoute.SIGN_IN} element={<Auth />} />
Do you really want to remove PageLayout?

2023-09-13 15:21 UTC, h0wter requested changes

2023-09-13 15:21 UTC, h0wter commented on frontend/src/libs/components/components.ts
> +export { TowTruckCard } from './tow-truck-card/tow-truck-card.js';
With this export there is a circular dependency because TowTruckCard imports Badge, Button, Icon from components.ts

2023-09-13 15:21 UTC, h0wter commented on frontend/src/libs/components/location-input/location-input.tsx
> +  onChange?: ((place: google.maps.LatLngLiteral) => void) | undefined;
Is optional props not enough?
```suggestion
  onChange?: (place: google.maps.LatLngLiteral) => void;
```

2023-09-13 15:21 UTC, h0wter commented on frontend/src/libs/components/tow-truck-card/styles.module.scss
> +.noFooter {
We decided to use kebab-case for naming classes.

2023-09-13 15:21 UTC, h0wter commented on frontend/src/pages/order/libs/components/order-form.tsx
> +import { orderForm } from 'shared/build/index.js';
Maybe re-export this from packages/orders/libs?

2023-09-13 15:21 UTC, h0wter commented on frontend/src/pages/order/libs/components/styles.module.scss
> +  padding: 20px 100px 35px;
Why are there two paddings? The second one overrides the first one.

2023-09-13 15:21 UTC, h0wter commented on frontend/src/pages/order/order.tsx
> +    navigator.geolocation.getCurrentPosition((location) => {
We have use-geolocation.hook, can we use it?

2023-09-13 15:21 UTC, h0wter commented on frontend/src/pages/order/order.tsx
> +      if (chosenTruck) {
Maybe redirect to Home Page if there is no chosenTruck?

2023-09-13 15:21 UTC, h0wter commented on frontend/src/slices/trucks/trucks.slice.ts
> +  chosenTruck: (TruckEntity & { driverId: number }) | undefined;
I think null is more appropriate for no value.

2023-09-15 10:50 UTC, kalinkaaaa14 commented
update pic in the description. price should be present in your last version

2023-09-15 13:33 UTC, kalinkaaaa14 requested changes

2023-09-15 13:33 UTC, kalinkaaaa14 commented on frontend/src/pages/order/order.tsx
> +            driverId: chosenTruck.driverId,
order creation flow was refactored a bit, now truck id should be passed https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/269

2023-09-15 13:33 UTC, kalinkaaaa14 commented on shared/src/packages/orders/orders.ts
> +  orderForm,
remove

2023-09-15 13:33 UTC, kalinkaaaa14 commented on shared/src/packages/orders/libs/validation-schemas/order-form.validation-schema.ts
> +const orderForm = joi.object<Omit<OrderCreateRequestDto, 'driverId'>, true>({
you should reuse orderCreateRequestBody, making two validation schemas for order in fe and be is a bad idea

2023-09-15 13:33 UTC, kalinkaaaa14 commented on backend/src/packages/map/map.controller.ts
> +      path: MapApiPath.ROOT,
the route for calculating the price should be in order controller
/orders/calculate-price

2023-09-15 13:33 UTC, kalinkaaaa14 commented on frontend/src/libs/components/form/form.tsx
> +      {price !== undefined && (
```suggestion
      {Boolean(price) && (
```

2023-09-15 14:01 UTC, DmytroVoronkov commented on shared/src/packages/orders/libs/validation-schemas/order-form.validation-schema.ts
> +const orderForm = joi.object<Omit<OrderCreateRequestDto, 'driverId'>, true>({
Form doesn`t work with this validation schema because it doesn`t contain truck id field

2023-09-16 10:27 UTC, Druxight requested changes

2023-09-16 10:27 UTC, Druxight commented on frontend/src/libs/components/tow-truck-card/styles.module.scss
> +  height: 138px;
its weird, can you use another approach for hiding footer ?

2023-09-16 10:27 UTC, Druxight commented on frontend/src/libs/components/tow-truck-card/tow-truck-card.tsx
> +              ${pricePerKm}/ <span className={styles.gray}>km</span>
The price format should be $price ($10)

2023-09-16 10:27 UTC, Druxight commented on frontend/src/libs/components/map/map.tsx
> +  center = { lat: 1, lng: 1 },
In my view its better to use current user lat lng as default center

2023-09-16 10:27 UTC, Druxight commented on frontend/src/pages/order/libs/components/order-form.tsx
> +        // TODO: Change driverId to truckId
What stops you from using the truckId now?

2023-09-16 10:33 UTC, PavloSukhinin requested changes

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/libs/components/location-input/location-input.tsx
> +  >();
```suggestion
  const [location, setLocation] = useState<
    google.maps.places.Autocomplete | null
  >(null);
```

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/libs/components/form/form.tsx
> +      )}
Generic components shouldn't know about specific stuff like price. I believe this whole Order Form can be custom form.
At least, let's try to create Component for it and define it in orderFormFields

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/libs/components/map/map.tsx
> +            });
keep components clean, business logic should be handled in thunks, and use slice to reflect changes

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/libs/components/form/form.tsx
> +          );
Don't like the fact that we'll pass handlers directly into form. But at least 
`onChange={LocationFieldName.START ? onLocationChange : onDestinationChange}`

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/libs/packages/map/map.package.ts
> +      : (nextPoint = firstLeg.steps[0].end_location);
avoid magic numbers, destructuring is preferred way to do this

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/libs/packages/map/map.package.ts
> +            size: new google.maps.Size(146, 168),
avoid magic numbers

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/libs/packages/map/libs/helpers/rotate-img.ts
> +  context?.translate(canvas.width / 2, canvas.height / 2);
create a helper for it

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/libs/packages/map/libs/helpers/rotate-img.ts
> +  const rotationRad = (rotationAngle * Math.PI) / 180;
we need a helper for it

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/libs/components/tow-truck-card/tow-truck-card.tsx
> +      }
getValidClassNames(styles.container, { [styles.noFooter]: !hasFooter } )

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/packages/orders/orders-api.ts
> +        hasAuth: false,
will we have another method for authenticated users?

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/pages/order/libs/components/order-form.tsx
> +        price={price}
can we pass through values?

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/pages/order/order.tsx
> +import { type Libraries, LoadScript } from '@react-google-maps/api';
import types from one place (~/libs/types/types.js)

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/pages/order/order.tsx
> +                distance={250}
mark it as TODO or FIXME. It will be lost otherwise

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/pages/order/order.tsx
> +                driverId={chosenTruck.driverId}
We merged that PR #269 , I believe we can solve this now

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/pages/order/order.tsx
> +                zoom={16}
why 16?

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/slices/trucks/trucks.slice.ts
> +  },
`chosenTruck: null`
I believe it's mock?

2023-09-16 10:33 UTC, PavloSukhinin commented on frontend/src/pages/order/order.tsx
> +            <div className={styles.left}>
But you already checked that truck exist
  ```
if (!chosenTruck) {
    navigate(AppRoute.ROOT);
  }
```

2023-09-16 17:59 UTC, PavloSukhinin requested changes

2023-09-16 17:59 UTC, PavloSukhinin commented on shared/package.json
> +    "react-dropzone": "14.2.3",
why it's in shared? 🤔

2023-09-16 17:59 UTC, PavloSukhinin commented on frontend/src/pages/order/order.tsx
> +            <div className={styles.left}>
So, do you need it?

2023-09-16 17:59 UTC, PavloSukhinin commented on frontend/src/libs/packages/map/map.package.ts
> +    origin = false,
please use be/have verbs for booleans

2023-09-16 17:59 UTC, PavloSukhinin commented on frontend/src/libs/packages/map/libs/helpers/rotate-img.ts
> +  (rotationAngle * Math.PI) / 180;
don't forget curly + return to avoid such line break

2023-09-16 19:30 UTC, kalinkaaaa14 requested changes

2023-09-16 19:30 UTC, kalinkaaaa14 commented on shared/src/packages/orders/libs/enums/orders-api-path.enum.ts
> +  CALCULATE_PRICE: '/calculatePrice',
```suggestion
  CALCULATE_PRICE: '/calculate-price',
```

2023-09-16 19:30 UTC, kalinkaaaa14 commented on frontend/src/pages/order/order.tsx
> +                rating={{ reviewCount: 5, averageRating: 4.3 }}
you can remove rating, because for now it will be not implemented

2023-09-16 19:30 UTC, kalinkaaaa14 commented on frontend/src/pages/order/libs/components/order-form.tsx
> +  ) => void;
add a separate type for this fn, and reuse in onStartLocChange, onEndLocationChange

2023-09-16 19:30 UTC, kalinkaaaa14 commented on frontend/src/pages/order/libs/components/libs/constants.ts
> +};
add TruckCarsQuantity enum in shared
```suggestion
const getCreateOrderDefaultPayload = (selectedTruckId: number): OrderCreateRequestDto => {
  return {
    customerName: '',
    customerPhone: '',
    scheduledTime: '',
    startPoint: '',
    endPoint: '',
    carsQty: TruckCarsQuantity.MIN,
    truckId: selectedTruckId
  }
}
```

2023-09-16 19:30 UTC, kalinkaaaa14 commented on frontend/src/libs/types/form.type.ts
> +  ) => void;
reuse created type for this fn here also

2023-09-16 19:30 UTC, kalinkaaaa14 commented on frontend/src/libs/packages/map/map.package.ts
> +      : (nextPoint = firstStep.end_location);
```suggestion
    const [firstLeg] = firstRoute.legs;
    const [firstStep, secondStep] = firstLeg.steps;

    const nextPoint = Boolean(secondStep) ? secondStep.start_location : firstStep.end_location;
```

2023-09-16 19:30 UTC, kalinkaaaa14 commented on frontend/src/libs/packages/map/map.package.ts
> +              TRUCK_IMG_HEIGHT / 2,
we should try to avoid magic numbers, use defined constants for them

2023-09-16 19:30 UTC, kalinkaaaa14 commented on frontend/src/libs/packages/map/libs/helpers/rotate-img.ts
rotate-img.helper

2023-09-16 19:30 UTC, kalinkaaaa14 commented on frontend/src/libs/components/map/map.tsx
> +  onPriceChange?: (price: number) => void;
why all of these properties are optional?

2023-09-16 19:30 UTC, kalinkaaaa14 commented on frontend/src/libs/components/map/map.tsx
> +  ]);
I don't think that dep array should be so wide.  I think we need to trigger recalculating order price on start & end point changing. Now we will trigger price recalculation every time on zooming, centering - which is not good. Also I suppose that now pricePerKm will be consistent, so when we will add a possibility to edit it, we will add it here

And what's the difference between destination and end point?

2023-09-16 19:46 UTC, MaxHopaytsa commented on frontend/src/slices/orders/actions.ts
> +  } catch (error) {
```suggestion
  } catch (error: unknown) {
```

2023-09-16 19:46 UTC, MaxHopaytsa commented on frontend/src/slices/orders/actions.ts
> +    notification.warning(getErrorMessage(error));
Perhaps it is better to use  notification.error ?
```suggestion
    notification.error(getErrorMessage(error));
```

2023-09-16 19:46 UTC, MaxHopaytsa commented on frontend/src/slices/orders/order.slice.ts
> +      .addCase(createOrder.pending, (state) => {
Wouldn't it be better to use **addMatcher** instead of **addCase** for all **pending** statuses at once? This should reduce the amount of code a bit.

2023-09-16 19:46 UTC, MaxHopaytsa commented on frontend/src/slices/orders/order.slice.ts
> +      .addCase(createOrder.rejected, (state) => {
The same for **rejected**

2023-09-18 07:25 UTC, PavloSukhinin approved these changes, later dismissed

2023-09-18 07:25 UTC, PavloSukhinin commented on frontend/src/slices/trucks/trucks.slice.ts
> +  },
Initial state should be null

2023-09-18 07:25 UTC, PavloSukhinin commented on frontend/src/pages/order/order.tsx
> +          <TowTruckCard truck={chosenTruck} distance={250} hasFooter={false} />
What 250 for?

2023-09-18 08:04 UTC, MaxHopaytsa approved these changes

2023-09-18 08:36 UTC, PavloSukhinin approved these changes, later dismissed

2023-09-18 08:50 UTC, kalinkaaaa14 commented on frontend/src/pages/order/libs/components/order-form.tsx
> +  onStartLocationChange: (
```suggestion
  onStartLocationChange: LocationChangeHandler
```

2023-09-18 08:50 UTC, kalinkaaaa14 commented on frontend/src/pages/order/libs/components/order-form.tsx
> +  ) => void;
```suggestion
  onEndLocationChange: LocationChangeHandler
```

2023-09-18 08:50 UTC, kalinkaaaa14 commented on frontend/src/libs/components/tow-truck-card/tow-truck-card.tsx
>                {rating.reviewCount} Reviews)
remove these comments

2023-09-18 08:50 UTC, kalinkaaaa14 commented on frontend/src/libs/components/tow-truck-card/tow-truck-card.tsx
> +  // rating,
remove

2023-09-18 08:50 UTC, kalinkaaaa14 commented on frontend/src/libs/components/tow-truck-card/tow-truck-card.tsx
> +  // };
remove

2023-09-18 08:50 UTC, kalinkaaaa14 commented on frontend/src/libs/components/tow-truck-card/tow-truck-card.tsx
> +// import { StarRating } from '../star-rating/star-rating.jsx';
remove

2023-09-18 08:50 UTC, kalinkaaaa14 commented on frontend/src/libs/components/location-input/location-input.tsx
> +  ) => void;
reuse created type for it

2023-09-18 09:01 UTC, kalinkaaaa14 approved these changes

2023-09-18 09:05 UTC, Druxight approved these changes

2023-09-18 09:05 UTC, merged