th-230:  Eval order price on the BE
BinaryStudioAcademy/bsa-2023-towhub pull request #240
Opened 2023-09-13 13:06 UTC by AlexVlaso

2023-09-13 16:35 UTC, MaxHopaytsa approved these changes

2023-09-14 07:09 UTC, PavloSukhinin requested changes

2023-09-14 07:09 UTC, PavloSukhinin commented on backend/src/libs/packages/config/config.package.ts
> +          env: 'VITE_APP_GOOGLE_MAPS_API_KEY',
remove `VITE_APP` part - we don't use VITE on BE

2023-09-14 07:09 UTC, PavloSukhinin commented on backend/src/packages/map/map.service.ts
> +    return response.data.rows[0].elements[0].distance;
avoid magic numbers

2023-09-14 07:09 UTC, PavloSukhinin commented on backend/src/packages/map/map.service.ts
> +    const km = distance.value / 1000;
let's introduce a helper for it

2023-09-14 07:55 UTC, mV22110702 approved these changes

2023-09-14 07:55 UTC, mV22110702 commented on backend/src/packages/map/map.service.ts
> +import { type Client, type Distance, TravelMode } from './libs/types/types.js';
TravelMode was used as enum. Should it be the part of types import, or should we make it as enum import instead?

2023-09-14 09:49 UTC, PavloSukhinin submitted a review, later dismissed

2023-09-14 10:50 UTC, kalinkaaaa14 commented on backend/src/packages/map/map.service.ts
> +    return +(pricePerKm * km).toFixed(2);
```suggestion
const orderPrice = (pricePerKm * km).toFixed(2);

return Number(orderPrice);
```

2023-09-14 10:50 UTC, kalinkaaaa14 commented on backend/src/packages/map/libs/helpers/helpers.ts
> +  return meters / 1000;
let's create const METERS_IN_ONE_KM = 1000;

2023-09-14 11:35 UTC, PavloSukhinin approved these changes

2023-09-14 11:36 UTC, kalinkaaaa14 approved these changes

2023-09-14 11:36 UTC, merged

2023-09-14 11:38 UTC, h0wter approved these changes

2023-09-14 11:38 UTC, h0wter commented on backend/src/packages/map/map.service.ts
> +  public async getPriceByDistance({
Is it correct to add price calculation logic in map service?