th-270: Fix authorized business-user can get data, change data, delete business of any business by id
BinaryStudioAcademy/bsa-2023-towhub pull request #272
Opened 2023-09-15 13:58 UTC by mV22110702

2023-09-16 10:24 UTC, MaxHopaytsa approved these changes

2023-09-18 06:58 UTC, AlexVlaso approved these changes

2023-09-18 11:01 UTC, kalinkaaaa14 submitted a review, later dismissed

2023-09-18 11:10 UTC, kalinkaaaa14 commented
actually during creation/updating/deletion - I guess we don't need to pass /:businessId in params and then check if logged in user has access to this operation

we can refactor it on /business/drivers, and found the businessId by authorized user, so we don't need to check if  logged in user has access to this operation, and don't need to pass param
but we can do it later, now it also will work correctly as you've added checks everywhere

2023-09-18 20:17 UTC, kalinkaaaa14 approved these changes, later dismissed

2023-09-19 07:52 UTC, PavloSukhinin requested changes

2023-09-19 07:52 UTC, PavloSukhinin commented on shared/src/libs/enums/app-error-message.enum.ts
>      'Invalid file input config was provided to file validator!',
```suggestion
  INVALID_QUERY: 'Invalid SQL query was provided!',
  ENTITY_NOT_FOUND: 'Requested entity not found!',
  ENTITY_ACCESS_DENIED: 'The user does not have access to the entity!',
  INVALID_FILE_INPUT_CONFIG:
    'Invalid file input config was provided to file validator!',
```
to keep messages in the same format

2023-09-21 13:34 UTC, kalinkaaaa14 submitted a review, later dismissed

2023-09-22 14:23 UTC, denred requested changes

2023-09-22 14:23 UTC, denred commented on backend/src/packages/business/business.service.ts
> +import { type TruckEntityT } from '../trucks/libs/types/types.js';
Why did you change "TruckEntity" to "TruckEntityT"?

2023-09-22 14:23 UTC, denred commented on backend/src/packages/business/business.service.ts
> +      throw new EntityAccessDeniedError({});
Why didn't you specify an error code?

2023-09-22 14:23 UTC, denred commented on backend/src/packages/business/business.service.ts
>        throw new NotFoundError({});
status code too

2023-09-22 14:23 UTC, denred commented on backend/src/packages/trucks/libs/types/types.ts
> +export { type TruckEntityT } from 'shared/build/index.js';
Really, why did you change it?

2023-09-22 17:20 UTC, mV22110702 commented on backend/src/packages/business/business.service.ts
> +import { type TruckEntityT } from '../trucks/libs/types/types.js';
Because for every entity type we prepended `T` to the end, so TruckEntity should also align with these namings.

2023-09-23 13:52 UTC, kalinkaaaa14 approved these changes, later dismissed

2023-09-23 14:25 UTC, MaxHopaytsa approved these changes

2023-09-23 14:46 UTC, merged