Task/th 22 create checkbox toggle radio components
BinaryStudioAcademy/bsa-2023-towhub pull request #34
Opened 2023-08-22 04:48 UTC by Some14u

Requires adjustments of colors and fonts. Waiting for corresponding pr.

Three components are done: checkbox, toggle and radio. All three components are derived from a single checkbox (because there is almost no difference in code, the difference is basically cosmetic).

All three can show error message and able to be disabled. I also added a simple animation setup to sass folder and used it to make toggling smoother.

2023-08-22 07:22 UTC, PavloSukhinin requested changes
Please, fix linter issues.

2023-08-22 07:22 UTC, PavloSukhinin commented on frontend/src/libs/components/checkbox/checkbox.tsx
> +import clsx from 'clsx';
Import clsx in a single place. Introduce a wrapper function getValidClassNames and use it everywhere 
`frontend/src/libs/helpers/get-valid-class-names/get-valid-class-names.helper.ts`

2023-08-22 07:22 UTC, PavloSukhinin commented on frontend/package.json
> +    "stylelint": "15.10.3"
Remove it. Already installed in root package.json

2023-08-22 07:22 UTC, PavloSukhinin commented on frontend/package.json
> +}
Enable pre-commit hooks

2023-08-22 07:22 UTC, PavloSukhinin commented on package.json
> +}
EOF

2023-08-22 07:22 UTC, PavloSukhinin commented on package.json
> +    "stylelint": "15.10.3",
Such changes must be coordinated and approved.

2023-08-22 07:22 UTC, PavloSukhinin commented on package-lock.json
> +        "stylelint": "15.10.2"
Are you just changed version in package.json manually? Packages should be changed only via npm

2023-08-22 07:22 UTC, PavloSukhinin commented on frontend/src/libs/components/checkbox/libs/enums/enums.ts
> +export { type CheckboxMode } from './checkbox-mode.enum.js';
run linter locally

2023-08-22 07:22 UTC, PavloSukhinin commented on frontend/src/libs/components/checkbox/libs/enums/checkbox-mode.enum.ts
> +export { type CheckboxMode };
missing eof

2023-08-22 07:22 UTC, PavloSukhinin commented on frontend/src/libs/components/checkbox/libs/enums/checkbox-mode.enum.ts
> +type CheckboxMode = 'checkbox' | 'toggle' | 'radio';
types <> enums

2023-08-22 07:22 UTC, PavloSukhinin commented on frontend/src/libs/components/checkbox/checkbox.tsx
> +  disabled?: boolean;
booleans should start with be/have verb

2023-08-22 07:22 UTC, PavloSukhinin commented on frontend/src/libs/components/checkbox/checkbox.tsx
> +        </div>
Appearance of this block will change dom and layout will "jump"

2023-08-22 07:22 UTC, PavloSukhinin commented on frontend/src/libs/components/checkbox/toggle.module.scss
> +}
This will be changed after introduction of global variables, right?

2023-08-22 07:22 UTC, PavloSukhinin commented on frontend/src/libs/components/checkbox/checkbox.tsx
> +  value = isRadio ? value : field.value;
Reassigning function parameters is considered a bad practice

2023-08-22 07:22 UTC, PavloSukhinin commented on frontend/src/libs/components/checkbox/common.module.scss
> +}
Most of those should be replaced with global values when they are present

2023-08-22 13:08 UTC, Some14u commented
@PavloSukhinin am i on the right track, or maybe something is missing?

2023-08-22 13:47 UTC, PavloSukhinin reviewed
Yes, but a few things to notice:
- use merge instead of rebase when working in team, your branch diff is already broken
- please fix conflicts

2023-08-22 19:04 UTC, kalinkaaaa14 commented on frontend/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600&display=swap" rel="stylesheet" />
fonts are already in dev branch, please pull existing code and reuse it

2023-08-22 19:04 UTC, kalinkaaaa14 commented on frontend/src/assets/css/styles.scss
> +}
this file should contain only imports of other scss

2023-08-22 19:04 UTC, kalinkaaaa14 commented on frontend/src/assets/img/checkmark.svg
it can be done with styles, without svg

2023-08-22 19:04 UTC, kalinkaaaa14 commented on frontend/src/libs/components/checkbox/checkbox.module.scss
> +  border: 2px solid var(--color);
rewrite please with colors from the main variables file

2023-08-23 09:39 UTC, closed without merging

2023-08-23 09:40 UTC, Some14u commented
This is closed because I resubmitted it in another pr:
https://github.com/BinaryStudioAcademy/bsa-2023-towhub/pull/54