th-337: Remove time field from order form
BinaryStudioAcademy/bsa-2023-towhub pull request #346
Opened 2023-09-23 15:17 UTC by DmytroVoronkov

- removed time field
- fixed form size
- added scroll to form
- set 50/50 ratio to page

![image](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/103923623/27a3d5b6-6370-4002-81b7-feb8881aefe2)

2023-09-23 15:21 UTC, h0wter approved these changes

2023-09-23 17:11 UTC, kalinkaaaa14 commented on frontend/src/pages/order/libs/components/styles.module.scss
> +  padding: 20px 15% 35px;
can we write padding in px?

2023-09-23 17:11 UTC, kalinkaaaa14 commented on frontend/src/pages/order/libs/components/libs/helpers.ts
> +  return currentDatetime.toISOString().slice(0, 16);
why do you need to use slice? 
add a separate helper for it

2023-09-23 17:17 UTC, kalinkaaaa14 commented
as we decided that we will be considering all orders = asap orders then actually scheduled time is not needed at our db. 
but it the future we can implement planning future orders, so ok, let's leave this column in order table

**but scheduled time it's better to calculate on be, so remove it from the default values on fe, and add to service layer calculation of scheduled time field.**

2023-09-24 14:09 UTC, h0wter approved these changes

2023-09-25 10:35 UTC, Druxight requested changes

2023-09-25 10:35 UTC, Druxight commented on shared/src/packages/orders/libs/enums/orders-validation-message.enum.ts
> +  PHONE_NOT_VALID: 'Must be 7-18 digits, start with +',
Same messages but different range format. 
```suggestion
  NAME_NOT_VALID: 'Must be 1 - 40 characters, start with a letter, no digits',
  PHONE_NOT_VALID: 'Must be 7 - 18 digits, start with +',
```

2023-09-25 12:33 UTC, AlexVlaso approved these changes

2023-09-26 10:16 UTC, denred approved these changes

2023-09-27 08:52 UTC, merged