th-357: Quality criteria fixes
BinaryStudioAcademy/bsa-2023-towhub pull request #362
Opened 2023-09-24 17:50 UTC by AlexVlaso

2023-09-24 18:46 UTC, h0wter commented
It's interesting to see what mistakes we've made :)

2023-09-24 19:02 UTC, Some14u requested changes

2023-09-24 19:02 UTC, Some14u commented on backend/src/packages/map/libs/constants/constants.ts
> +const DECIMAL = 2;
```suggestion
const PRECISION = 2;
```

2023-09-24 19:02 UTC, Some14u commented on frontend/src/libs/components/file-input/file-input.tsx
> +      const isNotEmptyRejectedFiles = rejectedFiles.length > ZERO_VALUE;
@kalinkaaaa14 are you sure this is the right way to do this?
I guess this is a overkill. The whole point of having "speaking names" is to assign a meaningful context to the number.
what do we add by changing 0 to ZERO_VALUE? Is it now more clear what it does? Moreover, such name prevents us form changing the value in the future (not relevant for this particular case, but nevertheless).

I doubt we should change each and every code 0 and 1 to ZERO_VALUE and ONE_VALUE just to be on the safe side about following the rule B31.

I suggest to revert it back to 0 and use a common sense and sanity every time we're following some particular rule.

2023-09-24 19:02 UTC, Some14u commented on frontend/src/libs/packages/map/libs/helpers/rotate-img.helper.ts
> +  context?.drawImage(image, getHalf(-image.width), getHalf(-image.height));
```suggestion
  context?.drawImage(image, -getHalf(image.width), -getHalf(image.height));
```

2023-09-25 06:49 UTC, h0wter commented on frontend/src/libs/components/form/libs/helpers/handle-server-error.helper.ts
> +import { PATH_DELIMITER } from '../consts/consts.js';
I'm guessing it's supposed to be constants?
```suggestion
import { PATH_DELIMITER } from '../constants/constants.js';
```

2023-09-25 08:24 UTC, h0wter approved these changes

2023-09-25 08:37 UTC, Some14u approved these changes

2023-09-26 07:23 UTC, kalinkaaaa14 commented on frontend/src/libs/components/star-rating/star-rating.tsx
>      }
is it actually used somewhere? if not, delete it please, because we are not having star rating now

2023-09-26 07:23 UTC, kalinkaaaa14 commented on frontend/src/libs/components/file-input/file-input.tsx
> +      const isNotEmptyRejectedFiles = rejectedFiles.length > ZERO_VALUE;
I suppose this comment was more general from those who checked our project, for zero value - ok, I agree that is not the right way 
the most appropriate way for check I think will be
const isNotEmptyRejectedFiles = Boolean(rejectedFiles.length);
 const isEmptyAcceptedFiles = !acceptedFiles.length;

can we do such way @AlexVlaso  ?

2023-09-26 07:46 UTC, kalinkaaaa14 approved these changes

2023-09-26 09:28 UTC, merged