th-15: Websockets integration
BinaryStudioAcademy/bsa-2023-towhub pull request #41
Opened 2023-08-22 11:45 UTC by DmytroVoronkov

- Created socket service in the backend 
- Created socket class in the client 
- Created shared socket enums 
- Created socket status on root page
![image](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/103923623/4323413c-6e51-4334-b6fc-24f7ffe78947)

2023-08-22 21:34 UTC, kalinkaaaa14 commented on backend/src/libs/packages/server-application/server-app.ts
> +import { socket } from '~/libs/packages/socket/socket.js';
```suggestion
import { socket as socketService } from '~/libs/packages/socket/socket.js';
```

2023-08-22 21:34 UTC, kalinkaaaa14 commented on backend/src/libs/packages/socket/socket.service.ts
> +    });
```suggestion
    this.io = new SocketServer(app.server, {
      cors: { origin: '*' },
    });
```

2023-08-22 21:34 UTC, kalinkaaaa14 commented on shared/src/libs/packages/socket/libs/enums/socket-namespaces.enum.ts
> +const SocketNamespaces = {
enum should be in singular form

2023-08-22 21:34 UTC, kalinkaaaa14 commented on shared/src/libs/packages/socket/libs/enums/server-socket-events.enum.ts
> +const ServerSocketEvents = {
enum should be in singular form

2023-08-22 21:34 UTC, kalinkaaaa14 commented on shared/src/libs/packages/socket/libs/enums/client-socket-events.enum.ts
> +const ClientSocketEvents = {
enum should be in singular form

2023-08-22 21:34 UTC, kalinkaaaa14 commented on frontend/package.json
> +    "stylelint": "15.10.2"
stylelint is in root package json

2023-08-22 21:34 UTC, kalinkaaaa14 commented on frontend/src/libs/packages/socket/socket-api.ts
rename to socket.package.ts

2023-08-23 08:02 UTC, kalinkaaaa14 approved these changes, later dismissed

2023-08-23 09:21 UTC, Druxight requested changes

2023-08-23 09:21 UTC, Druxight commented on frontend/src/libs/packages/socket/socket-api.ts
> +    return io('http://localhost:3001');
move to the .env file

2023-08-24 04:14 UTC, closed without merging