th-46: Create Loading component
BinaryStudioAcademy/bsa-2023-towhub pull request #52
Opened 2023-08-22 17:56 UTC by AlexVlaso

<img width="1421" alt="Снимок экрана 2023-08-22 в 20 50 50" src="https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/109801450/8edcddb8-6e51-4a29-b949-0c89fe956be6">

2023-08-22 21:12 UTC, kalinkaaaa14 commented on frontend/src/libs/components/spinner/spinner.tsx
> +import style from './spinner.module.scss';
```suggestion
import styles from './styles.module.scss';
```

2023-08-22 21:12 UTC, kalinkaaaa14 commented on frontend/src/libs/components/spinner/spinner.tsx
> +import React from 'react';
no need to use it

2023-08-22 21:12 UTC, kalinkaaaa14 commented on frontend/src/libs/components/spinner/spinner.tsx
> +  );
use early return here
if(isFullScreen ) { return one jsx; } return default jsx;

2023-08-23 07:08 UTC, kalinkaaaa14 commented on frontend/src/libs/components/spinner/spinner.tsx
> +import styles from './spinner.module.scss';
```suggestion
import styles from './styles.module.scss';
```

2023-08-23 08:48 UTC, Druxight requested changes

2023-08-23 08:48 UTC, Druxight commented on frontend/src/libs/components/spinner/spinner.tsx
> +  isFullScreen?: boolean;
Add size configuration (sm, md, lg) 
default md

2023-08-23 12:20 UTC, Druxight commented on frontend/src/libs/components/spinner/spinner.tsx
> +  const loaderClassName = `${styles.loader} ${styles[size]}`;
Use clsx (its already in the dev branch)

2023-08-23 14:55 UTC, kalinkaaaa14 approved these changes

2023-08-23 14:57 UTC, Druxight approved these changes

2023-08-23 15:19 UTC, merged