th-49: Update storage services
BinaryStudioAcademy/bsa-2023-towhub pull request #59
Opened 2023-08-23 10:03 UTC by MaxHopaytsa

- Modified the storage class to work with any type of data and added parsing logic and error handling accordingly. 
- Implemented local and session storage according to the existing Storage class

2023-08-23 14:59 UTC, Druxight requested changes

2023-08-23 14:59 UTC, Druxight commented on frontend/src/libs/packages/api/http-api.ts
> +  localStorage: IStorage;
there is no need to change the 'storage' to the 'local storage'

2023-08-23 14:59 UTC, Druxight commented on frontend/src/libs/packages/storage/libs/enums/storage-key.enum.ts
> +  ANOTHER_KEY: 'another_key',
another key ?

2023-08-23 18:32 UTC, Druxight commented on frontend/src/libs/packages/api/http-api.ts
> +  public constructor({ baseUrl, path, http, localStorage }: Constructor) {
there is no need to change `storage` to the `localStorage`

2023-08-23 18:32 UTC, Druxight commented on frontend/src/libs/packages/storage/storage.package.ts
> +class Storage<T> implements IStorage {
remove generic from class

2023-08-23 18:32 UTC, Druxight commented on frontend/src/libs/packages/storage/storage.package.ts
> +  ): Promise<void> {
`public set<T>(key: StorageKey, value: T): Promise<void> {
}`

2023-08-23 18:32 UTC, Druxight commented on frontend/src/packages/users/users.ts
> +  localStorage,
storage: LocalStorage

2023-08-23 18:32 UTC, Druxight commented on frontend/src/libs/packages/storage/storage.ts
> +const localStorage = new Storage(window.localStorage);
LocalStorage

2023-08-23 18:32 UTC, Druxight commented on frontend/src/libs/packages/storage/storage.ts
> +const sessionStorage = new Storage(window.sessionStorage);
SessionStorage

2023-08-24 08:39 UTC, Druxight requested changes

2023-08-24 08:39 UTC, Druxight commented on frontend/src/libs/packages/storage/storage.package.ts
> +  public drop(key: keyof typeof StorageKey): Promise<void> {
could you declare type above Storage class called StorageKeyValue = keyof typeof StorageKey and use it here 

key: StorageKeyValue

2023-08-24 11:54 UTC, PavloSukhinin requested changes

2023-08-24 11:54 UTC, PavloSukhinin commented on frontend/src/libs/packages/storage/storage.package.ts
> +import { ApplicationError } from 'shared/build/index.js';
Import it from `frontend/src/libs/exceptions/exceptions.js`

2023-08-24 11:54 UTC, PavloSukhinin commented on frontend/src/libs/packages/storage/storage.package.ts
> +  public set<T>(key: StorageKeyValue, value: T): Promise<void> {
Why do we use 'TOKEN' instead of 'token'?

2023-08-24 11:54 UTC, PavloSukhinin commented on frontend/src/libs/packages/storage/storage.package.ts
> +    } catch (error) {
```suggestion
    } catch (error: unknown) {
```

2023-08-24 11:54 UTC, PavloSukhinin commented on frontend/src/libs/packages/storage/storage.package.ts
> +        : Promise.resolve(JSON.parse(value) as T);
```suggestion
      return Promise.resolve(JSON.parse(value) as T)
```
JSON.parse(null) will return null 🤔

2023-08-24 13:13 UTC, PavloSukhinin approved these changes

2023-08-24 15:50 UTC, Druxight approved these changes

2023-08-24 15:50 UTC, merged