th-15: Websockets integration
BinaryStudioAcademy/bsa-2023-towhub pull request #72
Opened 2023-08-24 04:57 UTC by DmytroVoronkov

- Created websocket services in frontend and backend
- Created websocket handshake
![image](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/103923623/8b40a9d0-2bdd-4958-9f2b-b6ece9adda8b)

2023-08-24 07:58 UTC, Druxight requested changes

2023-08-24 07:58 UTC, Druxight commented on frontend/src/libs/components/app/app.tsx
> +    const io = socket.getInstance();
Create a separate service responsible for socket encapsulation

2023-08-25 08:48 UTC, kalinkaaaa14 commented on frontend/src/libs/components/app/app.tsx
> +import { SocketService } from '~/libs/packages/socket/socket.service';
```suggestion
import { SocketService } from '~/libs/packages/packages.js';
```

2023-08-25 08:48 UTC, kalinkaaaa14 commented on frontend/src/libs/packages/socket/libs/enums/enum.ts
file naming - enums.ts

2023-08-25 08:48 UTC, kalinkaaaa14 commented on frontend/src/libs/packages/socket/socket.service.ts
> +import { ClientSocketEvent } from '~/libs/packages/socket/libs/enums/enum.js';
you are already in ~/libs/packages/socket folder

2023-08-25 14:49 UTC, Druxight requested changes

2023-08-25 14:49 UTC, Druxight commented on frontend/src/libs/packages/socket/socket.package.ts
> +  public addListener(
why do we have 2 separate services when we can have only 1 ?

2023-08-26 11:10 UTC, PavloSukhinin commented on frontend/src/libs/packages/socket/libs/enums/enums.ts
> +export { ClientSocketEvent } from 'shared/build/index';
add file extension, please

2023-08-26 11:10 UTC, PavloSukhinin commented on shared/src/libs/packages/socket/libs/enums/socket-namespaces.enum.ts
> +  GLOBAL: '',
Let's give it a name? I believe 'global' is enough

2023-08-28 12:06 UTC, PavloSukhinin submitted a review, later dismissed

2023-08-28 19:28 UTC, kalinkaaaa14 approved these changes

2023-08-29 07:35 UTC, PavloSukhinin approved these changes

2023-08-29 09:07 UTC, merged