th-48: Dropdown component
BinaryStudioAcademy/bsa-2023-towhub pull request #74
Opened 2023-08-24 08:36 UTC by DmytroVoronkov

Add reusable dropdown component
![image](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/103923623/940544ef-78b0-45b3-9df5-e9a9d63534f2)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/103923623/bd253e82-84fe-4ad0-9cdf-2380b7019290)

2023-08-24 13:18 UTC, PavloSukhinin reviewed
Let's improve styling - component shouldn't have fixed width, add some margin for options

2023-08-24 15:13 UTC, Druxight commented
In my view we should get rid of focus border

2023-08-24 15:49 UTC, Druxight requested changes

2023-08-24 15:49 UTC, Druxight commented on frontend/src/libs/components/dropdown/dropdown.tsx
> +  const stylesConfig: StylesConfig = {
Move it out of FC and create function `getStyles({isMenuOpen}): StylesConfig` above the component.
Optimize function calls by using useCallback

2023-08-25 07:48 UTC, PavloSukhinin requested changes

2023-08-25 07:48 UTC, PavloSukhinin commented on frontend/src/libs/components/dropdown/dropdown.tsx
> +  const toggleMenu = useCallback(
`const handleToggleMenu`declaration of handlers/callbacks should start with `handle` word. 
callbacks passed via props should start with `on` (just like in Select below -   onMenuOpen)

2023-08-25 14:47 UTC, Druxight submitted a review, later dismissed

2023-08-26 11:13 UTC, PavloSukhinin requested changes

2023-08-26 11:13 UTC, PavloSukhinin commented on frontend/src/libs/components/dropdown/dropdown.tsx
> +type Option = { label: string; value: string };
Let's move it to `~/libs/types` and rename to SelectOption. We'll need it in case we want to declare options in page domain.

2023-08-28 12:07 UTC, PavloSukhinin commented on frontend/src/libs/components/dropdown/dropdown.tsx
> +import { type SelectOption } from '~/libs/types/select-option.type';
file extension, please

2023-08-28 14:09 UTC, PavloSukhinin approved these changes

2023-08-28 14:10 UTC, Druxight approved these changes

2023-08-28 14:49 UTC, merged