th-86: Modal component
BinaryStudioAcademy/bsa-2023-towhub pull request #94
Opened 2023-08-25 17:45 UTC by DmytroVoronkov

- Created Portal component
- Created Modal component
![image](https://github.com/BinaryStudioAcademy/bsa-2023-towhub/assets/103923623/e9bef4ce-c101-4a15-9406-a817f09255f1)

2023-08-25 17:48 UTC, DmytroVoronkov commented on frontend/src/libs/components/modal/modal.tsx
> +/* eslint-disable jsx-a11y/click-events-have-key-events */
I did not want to create unneccessary callbacks, so i added this line

2023-08-25 20:44 UTC, h0wter commented on frontend/src/libs/components/portal/portal.tsx
> +    const element = document.createElement('div');
Why not add an element for the portal directly to the `index.html`?
For example:
```
   <body>
     <div id="root"></div>
     <div id="modal-root"></div>
     <script type="module" src="/src/index.tsx"></script>
   </body>
```

2023-08-25 20:50 UTC, h0wter commented
Maybe add the ability to close the modal with `Esc` button?
Something like:
```
  const onKeyDown = useCallback(
    (e: KeyboardEvent) => {
      if (e.code === "Escape") {
        onClose();
      }
    },
    [onClose]
  );

  useEffect(() => {
    window.addEventListener("keydown", onKeyDown);

    return () => window.removeEventListener("keydown", onKeyDown);
  }, [onKeyDown]);
```

2023-08-28 14:39 UTC, PavloSukhinin requested changes

2023-08-28 14:39 UTC, PavloSukhinin commented on frontend/src/libs/components/modal/styles.module.scss
> +.modal {
Note for wide screens: I believe we should make modal width same as component inside it. Otherwise there will be a lot of empty space.

2023-08-30 07:29 UTC, PavloSukhinin requested changes

2023-08-30 07:29 UTC, PavloSukhinin commented on frontend/src/libs/components/modal/modal.tsx
> +    </div>
I thought we'll use `<dialog>` for modal itself, not just content

2023-08-30 09:21 UTC, PavloSukhinin approved these changes

2023-08-31 14:41 UTC, merged