th-81: Create order card component
BinaryStudioAcademy/bsa-2023-towhub pull request #95
Opened 2023-08-26 06:48 UTC by mV22110702

2023-08-29 11:27 UTC, Druxight submitted a review, later dismissed

2023-08-30 07:35 UTC, PavloSukhinin requested changes

2023-08-30 07:35 UTC, PavloSukhinin commented on frontend/src/libs/components/card/card.tsx
> +        <div className={style.header_image_container}>
I believe we decided to use camelCase for classnames

2023-08-30 07:35 UTC, PavloSukhinin commented on frontend/src/libs/components/card/card.tsx
> +            <span className={getValidClassNames('text-md')}>
do we need getValidClassNames here?

2023-08-30 07:35 UTC, PavloSukhinin commented on frontend/src/libs/components/card/styles.module.scss
> +@import "../../../assets/css/styles.scss";
```suggestion
@import "src/assets/css/styles.scss";
```

2023-08-31 15:58 UTC, Druxight submitted a review, later dismissed

2023-09-04 07:05 UTC, kalinkaaaa14 requested changes

2023-09-04 07:05 UTC, kalinkaaaa14 commented on frontend/src/libs/components/components.ts
> +export { PlainSvgIcon } from './plain-svg-icon/plain-svg-icon.jsx';
?
```suggestion
export { PlainSvgIcon } from './plain-svg-icon/plain-svg-icon.js';
```

2023-09-04 07:05 UTC, kalinkaaaa14 commented on frontend/src/libs/components/order-card/order-card.tsx
> +import style from './styles.module.scss';
```suggestion
import styles from './styles.module.scss';
```

2023-09-04 07:05 UTC, kalinkaaaa14 commented on frontend/src/libs/components/plain-svg-icon/maps/red-circle.svg
I don't like that these images will be stored inside libs/components/plain-svg-icon/maps, let's move it somewhere in assets/img? Or public/img

2023-09-04 07:05 UTC, kalinkaaaa14 commented on frontend/src/libs/components/plain-svg-icon/maps/maps.tsx
> +export { iconNameToPlainSvgMap } from './icon-name-to-plain-svg-map.jsx';
```suggestion
export { iconNameToPlainSvgMap } from './icon-name-to-plain-svg-map.js';
```

2023-09-04 07:05 UTC, kalinkaaaa14 commented on frontend/src/libs/components/order-card/styles.module.scss
> +@import "src/assets/css/styles.scss";
I prefer imports at the top of files

2023-09-04 07:05 UTC, kalinkaaaa14 commented on frontend/src/libs/components/order-card/order-card.tsx
> +  };
maybe let's create separate type for it called for example DriverProfileInfo or something like this?

2023-09-04 07:05 UTC, kalinkaaaa14 commented on frontend/src/libs/components/order-card/order-card.tsx
> +            {distanceLeft} km{distanceLeft > 1 && 's'}, {timespanLeft}
let's create a variable for calculation if there should be km or kms outside the jsx

2023-09-05 13:45 UTC, kalinkaaaa14 commented
don't forget to rerequest for a review, and remove labels (conflicts are resolved for ex)

2023-09-07 07:37 UTC, PavloSukhinin submitted a review, later dismissed

2023-09-07 08:18 UTC, kalinkaaaa14 commented on frontend/src/libs/components/plain-svg-icon/maps/icon-name-to-plain-svg-map.tsx
filename - icon-name-to-plain-svg.map
map name - iconNameToPlainSvg

2023-09-09 08:20 UTC, kalinkaaaa14 approved these changes

2023-09-09 09:18 UTC, PavloSukhinin approved these changes

2023-09-09 09:27 UTC, merged